### ISSUE TITLE
Crash With AppleCore

### ISSUE THREAD

**Issue by mcmso** [KenyMylankca/HarshenUniverse#28]
[crash-2019-05-23_20.08.23-client.txt](https://github.com/KenyMylankca/HarshenUniverse/files/3212042/crash-2019-05-23_20.08.23-client.txt)

**Comment by KenyMylankca** [comment]
report to spice of life carrot edition or apple core, it's not about HU.

**Comment by mcmso** [comment]
I understand. I will give you feedback as soon as possible

> 报告生活胡萝卜版或苹果核心的香料，它不是关于HU。

**Comment by mcmso** [comment]
I understand. I will give you feedback as soon as possible

**Comment by juliand665** [comment]
Sorry, but I don't think SoL: Carrot is doing anything wrong here. What's probably happening is that we're asking if your item stacks are edible before you run [`GlassContainerValues.reloadAll()`](https://github.com/KenyMylankca/HarshenUniverse/blob/675ba72b51f10d11d69f6c0b7d0ae6cc0c72781e/src/main/java/kenijey/harshenuniverse/enums/items/GlassContainerValues.java#L23-L37) (also it looks like `GlassContainerValues.EMPTY` is initialized to `GlassContainerValue.getContainerFromMeta(0)`, which again returns `GlassContainerValues.EMPTY`, resulting in it never getting initialized? not sure if that's related…)

**Comment by KenyMylankca** [comment]
empty glass container is initialized and in the game, and it works all fine. and the crash happens on #hasDrinkEffect, if it crash elsewhere the compiler would catch it. it wants an integer as input and returns true if there is any effect in the glass container meta item with the matching integer (meta id) and neither it returns false. so other mods should improve their questions they "ask" to game index.

**Comment by juliand665** [comment]
Well, you clearly have a null pointer exception somewhere, despite getting valid input. I think the problem is that the method is called before you build up `GlassContainerValues`, so it's using uninitialized values that it wouldn't think are null.

**Comment by KenyMylankca** [comment]
i will look into it once again.

**Comment by KenyMylankca** [comment]
@juliand665 hey ah, can't you make it **ask** if the item stacks are edible **after** running GlassContainerValues.reloadAll() ? becus i really tried to fix it in any way, but i couldn't find a way to make it compatible with SoL. i'm sorry.

**Comment by juliand665** [comment]
What if you just change `public final static void reloadAll() { … }` to `static { … }` (yes, just `static`, nothing else)? That should make it run on class load rather than after you request it to.

**Comment by KenyMylankca** [comment]
i tried it. same crash happens: 
```
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Spice of Life: Carrot Edition (solcarrot)
Caused by: java.lang.NullPointerException
	at kenijey.harshenuniverse.items.GlassContainer.hasDrinkEffect(GlassContainer.java:150)
	at kenijey.harshenuniverse.items.GlassContainer.getItemUseAction(GlassContainer.java:169)
	at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.isEdible(AppleCoreAccessorMutatorImpl.java:47)
	at squeek.applecore.api_impl.AppleCoreAccessorMutatorImpl.isFood(AppleCoreAccessorMutatorImpl.java:39)
	at com.cazsius.solcarrot.lib.FoodItemStacks.lambda$init$0(FoodItemStacks.java:37)
...
```

**Comment by juliand665** [comment]
All right, it turned out to be a two-part fix. First of all, you should be registering your glass container stuff (and everything else) in `init`, not `postInit`. Second, we shouldn't be indexing the food item stacks until `postInit`.

Moving those two things around fixes it, so I guess your part of the fix is getting rid of `postInit` and moving all that stuff to `init`. Also please look at the warnings your game is outputting on launch and fix them sometime, haha.

**Comment by KenyMylankca** [comment]
my postInit in commonproxy is empty. the server sided has few things, and tried to move them to init, but didn't fix it already...

**Comment by juliand665** [comment]
Right, hence it being a two-part fix. You need to change something around (which you did, although your client proxy has some stuff in `postInit` which you'd need to move too), and we need to move stuff around.

Try it out with [this build](https://github.com/KenyMylankca/HarshenUniverse/files/3258459/solcarrot-1.12.2-1.7.jar.zip); that should fix it in combination with your changes.

**Comment by KenyMylankca** [comment]
i will. thanks for helping.

**Comment by juliand665** [comment]
We just released [SoL: Carrot v1.7](https://minecraft.curseforge.com/projects/spice-of-life-carrot-edition/files/2723774)—if you make the changes i suggested and try it out with this build, everything should work :)

**Comment by KenyMylankca** [comment]
@juliand665 hey uhm, it still crashes, but not in the same way. please take a look:
[crash-2019-08-16_15.05.54-server.txt](https://github.com/KenyMylankca/HarshenUniverse/files/3509478/crash-2019-08-16_15.05.54-server.txt)

**Comment by KenyMylankca** [comment]
and yeah it crashes without SoL, it crashes with Apple Core.(i tried)

**Comment by KenyMylankca** [comment]
fixed
